# Generated by Django 4.0.6 on 2023-11-10 06:48

from django.db import migrations, models
import django.db.models.deletion
import leave.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('controller', '0008_depart_remove'),
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveAccepted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('accepted_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='controller.staff')),
            ],
            options={
                'verbose_name': 'Leave Accepted',
                'verbose_name_plural': 'Leave Accepted',
            },
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', leave.models.NameField(blank=True, max_length=15, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days', models.DecimalField(decimal_places=2, default=0, max_digits=1000)),
                ('reason', leave.models.NameField(blank=True, max_length=512, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('year', models.PositiveIntegerField(default=2023)),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Leave Application',
                'verbose_name_plural': 'Leave Applications',
            },
        ),
        migrations.CreateModel(
            name='LeaveBlockedPeriord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', leave.models.NameField(blank=True, max_length=512, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_finish', models.BooleanField(default=False)),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Leave Blocked',
                'verbose_name_plural': 'Leave Blocked',
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', leave.models.NameField(blank=True, max_length=15, null=True)),
                ('name', leave.models.NameField(max_length=50)),
                ('descriptions', leave.models.NameField(blank=True, max_length=512, null=True)),
                ('is_counted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Leave Type',
                'verbose_name_plural': 'Leave Types',
            },
        ),
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', leave.models.NameField(blank=True, max_length=50, null=True)),
                ('date', models.DateField()),
                ('description', leave.models.NameField(blank=True, max_length=512, null=True)),
                ('is_annual_repeated', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Public Holiday',
                'verbose_name_plural': 'Public Holiday',
            },
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', leave.models.NameField(blank=True, max_length=50, null=True)),
                ('number', models.PositiveIntegerField()),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Roster',
                'verbose_name_plural': 'Rosters',
            },
        ),
        migrations.CreateModel(
            name='WorkingDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', leave.models.NameField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('type_work', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dictionary.dictionaryitem')),
            ],
            options={
                'verbose_name': 'Working Day',
                'verbose_name_plural': 'Working Days',
            },
        ),
        migrations.CreateModel(
            name='LeaveRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('year', models.PositiveIntegerField(default=2023)),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='leave.roster')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='controller.staff')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dictionary.dictionaryitem')),
            ],
            options={
                'verbose_name': 'Leave Roster',
                'verbose_name_plural': 'Leave Rosters',
            },
        ),
        migrations.CreateModel(
            name='LeaveRejected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', leave.models.NameField(blank=True, max_length=512, null=True)),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='leave.leaveapplication')),
                ('rejected_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='controller.staff')),
            ],
            options={
                'verbose_name': 'Leave Rejected',
                'verbose_name_plural': 'Leave Rejected',
            },
        ),
        migrations.CreateModel(
            name='LeaveDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('hours', models.DecimalField(decimal_places=2, default=0, max_digits=1000)),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('duration_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dictionary.dictionaryitem')),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='leave.leaveapplication')),
            ],
            options={
                'verbose_name': 'Leave Duration',
                'verbose_name_plural': 'Leave Durations',
            },
        ),
        migrations.CreateModel(
            name='LeaveDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.PositiveIntegerField()),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='leave.leavetype')),
            ],
            options={
                'verbose_name': 'Leave Days',
                'verbose_name_plural': 'Leave Days',
            },
        ),
        migrations.CreateModel(
            name='LeaveComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', leave.models.NameField(blank=True, max_length=512, null=True)),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('commented_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='controller.staff')),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='leave.leaveapplication')),
            ],
            options={
                'verbose_name': 'Leave Comment',
                'verbose_name_plural': 'Leave Comments',
            },
        ),
        migrations.CreateModel(
            name='LeaveCanceled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', leave.models.NameField(blank=True, max_length=512, null=True)),
                ('utilised_days', models.PositiveIntegerField()),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('canceled_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='controller.staff')),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='leave.leaveaccepted')),
            ],
            options={
                'verbose_name': 'Leave Cnaceled',
                'verbose_name_plural': 'Leave Cnaceled',
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entitlement', models.PositiveIntegerField()),
                ('utilised', models.PositiveIntegerField()),
                ('balance', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField(default=2023)),
                ('is_used', models.BooleanField(default=False)),
                ('is_expired', models.BooleanField(default=False)),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='controller.staff')),
            ],
            options={
                'verbose_name': 'Leave Balance',
                'verbose_name_plural': 'Leave Balance',
            },
        ),
        migrations.CreateModel(
            name='LeaveAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='controller.staff')),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='leave.leaveapplication')),
            ],
            options={
                'verbose_name': 'Leave Assignment',
                'verbose_name_plural': 'Leave Assignments',
            },
        ),
        migrations.CreateModel(
            name='LeaveApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='controller.staff')),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='leave.leaveapplication')),
            ],
            options={
                'verbose_name': 'Leave Approval',
                'verbose_name_plural': 'Leave Approval',
            },
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='leave.leavetype'),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='controller.staff'),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dictionary.dictionaryitem'),
        ),
        migrations.AddField(
            model_name='leaveaccepted',
            name='leave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='leave.leaveapplication'),
        ),
        migrations.AddField(
            model_name='leaveaccepted',
            name='roster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='leave.roster'),
        ),
        migrations.AddField(
            model_name='leaveaccepted',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dictionary.dictionaryitem'),
        ),
    ]
