# Generated by Django 4.0.6 on 2023-11-10 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
        ('leave', '0001_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='counting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dictionary.dictionaryitem'),
            preserve_default=False,
        ),
    ]
