# Generated by Django 4.0.6 on 2023-11-10 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_leave_counting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavetype',
            name='is_counted',
        ),
    ]
