# Generated by Django 4.0.6 on 2023-11-14 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_leave_remove'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavedays',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='leave_type_days', to='leave.leavetype'),
        ),
    ]
