# Generated by Django 4.0.6 on 2023-11-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_assignemtn'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveassignment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
