# Generated by Django 4.0.6 on 2023-11-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_assignemtn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaveapplication',
            old_name='days',
            new_name='total_days',
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='working_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000),
        ),
    ]
