# Generated by Django 4.0.6 on 2023-11-15 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0006_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalance',
            name='leave_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='leave.leavetype'),
        ),
        migrations.AlterField(
            model_name='leaveduration',
            name='leave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='application_duration', to='leave.leaveapplication'),
        ),
    ]
