# Generated by Django 4.0.6 on 2023-11-20 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0007_balance_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavecomment',
            name='accept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='leave.leaveaccepted'),
        ),
        migrations.AddField(
            model_name='leavecomment',
            name='approve',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='leave.leaveapproval'),
        ),
        migrations.AddField(
            model_name='leavecomment',
            name='assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='leave.leaveassignment'),
        ),
        migrations.AddField(
            model_name='leavecomment',
            name='cancel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='leave.leavecanceled'),
        ),
        migrations.AddField(
            model_name='leavecomment',
            name='reject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='leave.leaverejected'),
        ),
    ]
