# Generated by Django 4.0.6 on 2023-11-20 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0010_bank_type'),
        ('leave', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveassignment',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='assigned_by', to='controller.staff'),
        ),
    ]
