# Generated by Django 4.0.6 on 2023-11-21 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0009_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveaccepted',
            name='leave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='leave_accept', to='leave.leaveapplication'),
        ),
        migrations.AlterField(
            model_name='leaveapproval',
            name='leave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='leave_approve', to='leave.leaveapplication'),
        ),
        migrations.AlterField(
            model_name='leavecomment',
            name='accept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='accept_comment', to='leave.leaveaccepted'),
        ),
        migrations.AlterField(
            model_name='leavecomment',
            name='approve',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='approve_comment', to='leave.leaveapproval'),
        ),
        migrations.AlterField(
            model_name='leavecomment',
            name='assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='assigned_comment', to='leave.leaveassignment'),
        ),
        migrations.AlterField(
            model_name='leavecomment',
            name='cancel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='cancel_comment', to='leave.leavecanceled'),
        ),
        migrations.AlterField(
            model_name='leavecomment',
            name='reject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='reject_comment', to='leave.leaverejected'),
        ),
        migrations.CreateModel(
            name='LeaveCountingDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('year', models.PositiveIntegerField(default=2023)),
                ('is_counted', models.BooleanField(default=False)),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='leave.leaveapplication')),
            ],
            options={
                'verbose_name': 'Leave Counting Days',
                'verbose_name_plural': 'Leave Counting Days',
            },
        ),
    ]
