# Generated by Django 4.0.6 on 2023-11-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0010_countingDays'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavecountingdays',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
