# Generated by Django 4.0.6 on 2024-05-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0011_cancel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='year',
            field=models.PositiveIntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='year',
            field=models.PositiveIntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='leavecountingdays',
            name='year',
            field=models.PositiveIntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='leaveroster',
            name='year',
            field=models.PositiveIntegerField(default=2024),
        ),
    ]
