# Generated by Django 4.0.6 on 2024-11-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0012_finance'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
