# Generated by Django 4.0.6 on 2024-11-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0013_leave_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebalance',
            name='balance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='entitlement',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='utilised',
            field=models.IntegerField(),
        ),
    ]
