# Generated by Django 4.0.6 on 2024-11-15 09:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0014_leave_balcne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebalance',
            name='balance',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(-1000)]),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='entitlement',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(-1000)]),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='utilised',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(-1000)]),
        ),
    ]
