# Generated by Django 4.0.6 on 2025-02-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0015_leave_balcne_neg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='year',
            field=models.PositiveIntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='year',
            field=models.PositiveIntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name='leavecountingdays',
            name='year',
            field=models.PositiveIntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name='leaveroster',
            name='year',
            field=models.PositiveIntegerField(default=2025),
        ),
    ]
