# Generated by Django 4.0.6 on 2025-04-02 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0018_cpf'),
        ('leave', '0016_keen'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leaveapplication',
            unique_together={('staff', 'leave_type', 'is_active')},
        ),
    ]
