# Generated by Django 4.0.6 on 2026-02-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0017_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='year',
            field=models.PositiveIntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='year',
            field=models.PositiveIntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name='leavecountingdays',
            name='year',
            field=models.PositiveIntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name='leaveroster',
            name='year',
            field=models.PositiveIntegerField(default=2026),
        ),
    ]
