# Generated by Django 4.0.6 on 2025-06-27 07:23

from django.db import migrations, models
import gateway.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_date', models.DateTimeField(blank=True, null=True)),
                ('branch_code', gateway.models.NameField(blank=True, max_length=50, null=True)),
                ('emplayee_name', gateway.models.NameField(blank=True, max_length=150, null=True)),
                ('emplayee_gender', gateway.models.NameField(blank=True, max_length=10, null=True)),
                ('emplayee_date_birth', models.DateField(blank=True, null=True)),
                ('emplayee_identity_type', gateway.models.NameField(blank=True, max_length=150, null=True)),
                ('emplayee_identity_number', gateway.models.NameField(blank=True, max_length=150, null=True)),
                ('emplayee_position', gateway.models.NameField(blank=True, max_length=150, null=True)),
                ('emplayee_position_category', gateway.models.NameField(blank=True, max_length=150, null=True)),
                ('emplayee_status', gateway.models.NameField(blank=True, max_length=150, null=True)),
                ('emplayee_department', gateway.models.NameField(blank=True, max_length=150, null=True)),
                ('emplayee_appointment_date', models.DateField(blank=True, null=True)),
                ('emplayee_nationality', gateway.models.NameField(blank=True, max_length=150, null=True)),
                ('emplayee_last_promotion_date', models.DateField(blank=True, null=True)),
                ('emplayee_basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('emplayee_benefit', gateway.models.NameField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Employee Data',
                'verbose_name_plural': 'Employee Data',
            },
        ),
    ]
