# Generated by Django 4.0.6 on 2025-06-27 19:59

import django.contrib.postgres.fields
from django.db import migrations, models
import gateway.models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0001_employee_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedata',
            name='emplayee_appointment_date',
            field=gateway.models.NameField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='emplayee_benefit',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=150), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='emplayee_date_birth',
            field=gateway.models.NameField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='emplayee_department',
            field=gateway.models.NameField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='emplayee_identity_number',
            field=gateway.models.NameField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='emplayee_identity_type',
            field=gateway.models.NameField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='emplayee_last_promotion_date',
            field=gateway.models.NameField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='emplayee_nationality',
            field=gateway.models.NameField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='emplayee_position_category',
            field=gateway.models.NameField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='emplayee_status',
            field=gateway.models.NameField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='reporting_date',
            field=gateway.models.NameField(blank=True, max_length=50, null=True),
        ),
    ]
