from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from leave.views import *

#-----------------------------------urls---------------------------------------------

urlpatterns = [
	path('leave-type', LeaveTypeAdd.as_view()),
	path('leave-type/update/<int:pk>', LeaveTypeUpdate.as_view()),
	path('leave-type/list', LeaveTypeList.as_view()),
	path('leave-days/list', LeaveDaysList.as_view()),
	path('leave-days', LeaveDaysAdd.as_view()),
	path('leave-days/update/<int:pk>', LeaveDaysUpdate.as_view()),
	path('leave-application', LeaveApplicationAdd.as_view()),
	path('leave-application/update/<int:pk>', LeaveApplicationUpdate.as_view()),
	path('leave-application/details/<int:pk>', LeaveApplicationDetail.as_view()),
	path('leave-application/list', LeaveApplicationList.as_view()),
	path('leave-counting-days/list', LeaveCountingDaysList.as_view()),
	path('leave-counting-days', LeaveCountingDaysAdd.as_view()),
	path('leave-counting-days/update/<int:pk>', LeaveCountingDaysUpdate.as_view()),
	path('leave-duration', LeaveDurationAdd.as_view()),
	path('leave-duration/update/<int:pk>', LeaveDurationUpdate.as_view()),
	path('leave-duration/list', LeaveDurationList.as_view()),
	path('leave-assignment', LeaveAssignmentAdd.as_view()),
	path('leave-status/<int:pk>', LeaveApplicationChangeStatus.as_view()),
	path('leave-assignment/update/<int:pk>', LeaveAssignmentUpdate.as_view()),
	path('leave-assignment/list', LeaveAssignmentList.as_view()),
	path('leave-approval', LeaveApprovalAdd.as_view()),
	path('leave-approval/update/<int:pk>', LeaveApprovalUpdate.as_view()),
	path('leave-approval/list', LeaveApprovalList.as_view()),
	path('leave-comment', LeaveCommentAdd.as_view()),
	path('leave-comment/update/<int:pk>', LeaveCommentUpdate.as_view()),
	path('leave-comment/list', LeaveCommentList.as_view()),
	path('leave-accepted', LeaveAcceptedAdd.as_view()),
	path('leave-accepted/update/<int:pk>', LeaveAcceptedUpdate.as_view()),
	path('leave-accepted/list', LeaveAcceptedList.as_view()),
	path('leave-rejected', LeaveRejectedAdd.as_view()),
	path('leave-rejected/update/<int:pk>', LeaveRejectedUpdate.as_view()),
	path('leave-rejected/list', LeaveRejectedList.as_view()),
	path('leave-canceled', LeaveCanceledAdd.as_view()),
	path('leave-canceled/update/<int:pk>', LeaveCanceledUpdate.as_view()),
	path('leave-canceled/list', LeaveCanceledList.as_view()),
	path('leave-balance', LeaveBalanceAdd.as_view()),
	path('leave-balance/update/<int:pk>', LeaveBalanceUpdate.as_view()),
	path('leave-balance/list', LeaveBalanceList.as_view()),
	path('roster', RosterAdd.as_view()),
	path('roster/update/<int:pk>', RosterUpdate.as_view()),
	path('roster/list', RosterList.as_view()),
	path('leave-roster', LeaveRosterAdd.as_view()),
	path('leave-roster/update/<int:pk>', LeaveRosterUpdate.as_view()),
	path('leave-roster/list', LeaveRosterList.as_view()),
	path('leave-blocked', LeaveBlockedPeriordAdd.as_view()),
	path('leave-blocked/update/<int:pk>', LeaveBlockedPeriordUpdate.as_view()),
	path('leave-blocked/list', LeaveBlockedPeriordList.as_view()),
	path('holiday', PublicHolidayAdd.as_view()),
	path('holiday/update/<int:pk>', PublicHolidayUpdate.as_view()),
	path('holiday/list', PublicHolidayList.as_view()),
	path('work-day', WorkingDaysAdd.as_view()),
	path('work-day/update/<int:pk>', WorkingDaysUpdate.as_view()),
	path('work-day/list', WorkingDaysList.as_view()),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)