# Generated by Django 4.0.6 on 2023-11-02 16:27

import controller.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_code', controller.models.NameField(blank=True, max_length=15, null=True)),
                ('branch_name', controller.models.NameField(blank=True, max_length=150, null=True)),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('branch_location', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dictionary.dictionaryitem')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_code', controller.models.NameField(blank=True, max_length=15, null=True)),
                ('department_name', controller.models.NameField(blank=True, max_length=150, null=True)),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('parent_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='parent', to='controller.department')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departmentes',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', controller.models.NameField(blank=True, max_length=5, null=True)),
                ('full_name', controller.models.NameField(blank=True, max_length=150, null=True)),
                ('dob', models.DateField()),
                ('address', controller.models.NameField(blank=True, max_length=50, null=True)),
                ('phone_number', controller.models.NameField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('id_number', controller.models.NameField(blank=True, max_length=50, null=True)),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='gender', to='dictionary.dictionaryitem')),
                ('id_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='id_type', to='dictionary.dictionaryitem')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
            },
        ),
        migrations.CreateModel(
            name='StaffBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit_provider', controller.models.NameField(blank=True, max_length=150, null=True)),
                ('no_dependent', models.PositiveIntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
                ('remaks', controller.models.NameField(blank=True, max_length=512, null=True)),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('benefit_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='benefit_type', to='dictionary.dictionaryitem')),
            ],
            options={
                'verbose_name': 'Staff Benefit',
                'verbose_name_plural': 'Staff Benefits',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='controller.person')),
                ('staff_opf', models.PositiveIntegerField(null=True)),
                ('doh', models.DateField()),
                ('job_title', controller.models.NameField(blank=True, max_length=50, null=True)),
                ('employment_status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='status', to='dictionary.dictionaryitem')),
            ],
            bases=('controller.person',),
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', controller.models.NameField(blank=True, max_length=15, null=True)),
                ('dos', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('supervise_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='super_type', to='dictionary.dictionaryitem')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='staff', to='controller.staff')),
            ],
            options={
                'verbose_name': 'Supervisor',
                'verbose_name_plural': 'Supervisors',
            },
        ),
        migrations.CreateModel(
            name='StaffBenefitDependent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('remaks', controller.models.NameField(blank=True, max_length=512, null=True)),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('benefit', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='controller.staffbenefit')),
                ('benefit_dependent', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='benefit_dependent', to='controller.person')),
            ],
            options={
                'verbose_name': 'Staff Benefit Dependent',
                'verbose_name_plural': 'Staff Benefit Dependents',
            },
        ),
        migrations.CreateModel(
            name='DepartmentHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='controller.department')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='controller.supervisor')),
            ],
            options={
                'verbose_name': 'Department Head',
                'verbose_name_plural': 'Department Head',
            },
        ),
        migrations.CreateModel(
            name='BranchManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='controller.branch')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='controller.supervisor')),
            ],
            options={
                'verbose_name': 'Branch Manager',
                'verbose_name_plural': 'Branch Managers',
            },
        ),
        migrations.CreateModel(
            name='StaffDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='controller.branch')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='controller.department')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='controller.staff')),
            ],
            options={
                'verbose_name': 'Staff Department',
                'verbose_name_plural': 'Staff Department',
            },
        ),
        migrations.AddField(
            model_name='staffbenefit',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='controller.staff'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', controller.models.NameField(blank=True, max_length=150, null=True)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='media/documents/')),
                ('is_active', models.BooleanField(default=True)),
                ('remaks', controller.models.NameField(blank=True, max_length=512, null=True)),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='document_type', to='dictionary.dictionaryitem')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='controller.staff')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
    ]
