# Generated by Django 4.0.6 on 2023-11-03 03:00

import controller.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', controller.models.NameField(blank=True, max_length=15, null=True)),
                ('name', controller.models.NameField(blank=True, max_length=150, null=True)),
                ('ended_year', models.PositiveIntegerField()),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Qualification',
                'verbose_name_plural': 'Qualifications',
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='branch_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='branch_type', to='dictionary.dictionaryitem'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='branch_location', to='dictionary.dictionaryitem'),
        ),
    ]
