# Generated by Django 4.0.6 on 2023-11-03 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0002_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='parent_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='parent', to='controller.branch'),
        ),
    ]
