# Generated by Django 4.0.6 on 2023-11-04 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
        ('controller', '0003_parent_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_size',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='staff',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='staffqualification',
            name='qualification_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='type', to='dictionary.dictionaryitem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffqualification',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='controller.staff'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='job_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='title', to='dictionary.dictionaryitem'),
            preserve_default=False,
        ),
    ]
