# Generated by Django 4.0.6 on 2023-11-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0004_staff_qualif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_opf',
            field=models.PositiveIntegerField(unique=True),
            preserve_default=False,
        ),
    ]
