# Generated by Django 4.0.6 on 2023-11-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0005_opf_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchmanager',
            name='removed_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='staffdepartment',
            name='removed_at',
            field=models.DateField(null=True),
        ),
    ]
