# Generated by Django 4.0.6 on 2023-11-08 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0006_removed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='doe',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='staffdepartment',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='staff_department', to='controller.staff'),
        ),
    ]
