# Generated by Django 4.0.6 on 2023-11-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0007_doe'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmenthead',
            name='removed_at',
            field=models.DateField(null=True),
        ),
    ]
