# Generated by Django 4.0.6 on 2023-11-16 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
        ('controller', '0008_depart_remove'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='doh',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='employment_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='status', to='dictionary.dictionaryitem'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='job_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='title', to='dictionary.dictionaryitem'),
        ),
    ]
