# Generated by Django 4.0.6 on 2023-11-16 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
        ('controller', '0009_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='bank_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bank_type', to='dictionary.dictionaryitem'),
        ),
    ]
