# Generated by Django 4.0.6 on 2023-11-29 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
        ('controller', '0010_bank_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffdepartment',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='dictionary.dictionaryitem'),
        ),
    ]
