# Generated by Django 4.0.6 on 2023-12-04 18:01

import controller.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0011_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', controller.models.NameField(blank=True, max_length=50, null=True)),
                ('name', controller.models.NameField(blank=True, max_length=150, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Security Fund',
                'verbose_name_plural': 'Security Fund',
            },
        ),
        migrations.CreateModel(
            name='StaffSecurityFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='controller.securityfund')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='controller.staff')),
            ],
            options={
                'verbose_name': 'Staff Security Fund',
                'verbose_name_plural': 'Staff Security Funds',
            },
        ),
    ]
