# Generated by Django 4.0.6 on 2024-06-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0012_payee_deductions'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
