# Generated by Django 4.0.6 on 2024-07-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0013_update_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffqualification',
            name='code',
        ),
        migrations.AddField(
            model_name='staffqualification',
            name='qualification_doc',
            field=models.CharField(blank=True, max_length=10000000, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_file',
            field=models.CharField(blank=True, max_length=10000000, null=True),
        ),
    ]
