# Generated by Django 4.0.6 on 2024-07-19 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0014_qlf_doc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='document_size',
        ),
    ]
