# Generated by Django 4.0.6 on 2025-02-03 05:32

import controller.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0015_remove_doc_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='keen_number',
            field=controller.models.NameField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='next_keen',
            field=controller.models.NameField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
