# Generated by Django 4.0.6 on 2025-02-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0016_keen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='person',
            name='id_type',
        ),
        migrations.AddField(
            model_name='person',
            name='nida',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='zanid',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
