# Generated by Django 4.0.6 on 2025-03-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0017_nida'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staff_cpf',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
