# Generated by Django 4.0.6 on 2025-08-13 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_dict_char'),
        ('controller', '0018_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffdepartment',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='position', to='dictionary.dictionaryitem'),
        ),
    ]
