# Generated by Django 4.0.6 on 2026-02-07 07:04

import controller.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0019_kpi'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', controller.models.NameField(blank=True, max_length=50, null=True)),
                ('name', controller.models.NameField(blank=True, max_length=150, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Health Fund',
                'verbose_name_plural': 'Health Funds',
            },
        ),
        migrations.AddField(
            model_name='staff',
            name='staff_category',
            field=models.CharField(default='primary', max_length=20),
        ),
        migrations.CreateModel(
            name='StaffHealthFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='controller.healthfund')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='controller.staff')),
            ],
            options={
                'verbose_name': 'Staff Health Fund',
                'verbose_name_plural': 'Staff Health Funds',
            },
        ),
    ]
