# Generated by Django 4.0.6 on 2026-02-09 10:26

import controller.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0020_health'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityfund',
            name='account',
            field=controller.models.NameField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='securityfund',
            name='branch',
            field=controller.models.NameField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='securityfund',
            name='ledger',
            field=controller.models.NameField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='securityfund',
            name='sub_ledger',
            field=controller.models.NameField(blank=True, max_length=150, null=True),
        ),
    ]
