# Generated by Django 4.0.6 on 2026-04-24 08:24

import controller.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0021_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_exit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='reason',
            field=controller.models.NameField(blank=True, max_length=512, null=True),
        ),
    ]
