# Generated by Django 4.0.6 on 2026-04-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0022_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='doe',
            field=models.DateField(null=True),
        ),
    ]
