# Generated by Django 4.0.6 on 2023-11-22 07:06

from django.db import migrations, models
import django.db.models.deletion
import payroll.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('controller', '0010_bank_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', payroll.models.NameField(blank=True, max_length=50, null=True)),
                ('name', payroll.models.NameField(blank=True, max_length=512, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=1000)),
                ('percentage', models.FloatField(default=0)),
                ('is_percentage', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Allowance',
                'verbose_name_plural': 'Allowances',
            },
        ),
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', payroll.models.NameField(blank=True, max_length=50, null=True)),
                ('name', payroll.models.NameField(blank=True, max_length=512, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=1000)),
                ('percentage', models.FloatField(default=0)),
                ('is_percentage', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Deduction',
                'verbose_name_plural': 'Deductions',
            },
        ),
        migrations.CreateModel(
            name='StaffSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', payroll.models.NameField(blank=True, max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='controller.staff')),
            ],
            options={
                'verbose_name': 'Staff Salary',
                'verbose_name_plural': 'Staff Salary',
            },
        ),
        migrations.CreateModel(
            name='StaffDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', payroll.models.NameField(blank=True, max_length=50, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('deduction', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='payroll.deduction')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='controller.staff')),
            ],
            options={
                'verbose_name': 'Staff Deduction',
                'verbose_name_plural': 'Staff Deductions',
            },
        ),
        migrations.CreateModel(
            name='StaffAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', payroll.models.NameField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('allowance', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='payroll.allowance')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='controller.staff')),
            ],
            options={
                'verbose_name': 'Staff Allowance',
                'verbose_name_plural': 'Staff Allowances',
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=1000)),
                ('total_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=1000)),
                ('total_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=1000)),
                ('payee', models.DecimalField(decimal_places=2, default=0, max_digits=1000)),
                ('security_fund', models.DecimalField(decimal_places=2, default=0, max_digits=1000)),
                ('month', models.PositiveIntegerField(default=11)),
                ('year', models.PositiveIntegerField(default=2023)),
                ('is_active', models.BooleanField(default=True)),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='controller.staff')),
            ],
            options={
                'verbose_name': 'Payroll',
                'verbose_name_plural': 'Payrolls',
            },
        ),
        migrations.CreateModel(
            name='MonthlyDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=1000)),
                ('month', models.PositiveIntegerField(default=11)),
                ('year', models.PositiveIntegerField(default=2023)),
                ('is_active', models.BooleanField(default=True)),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('deduction', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='payroll.deduction')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='controller.staff')),
            ],
            options={
                'verbose_name': 'Monthly Deduction',
                'verbose_name_plural': 'Monthly Deductions',
            },
        ),
        migrations.CreateModel(
            name='MonthlyAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=1000)),
                ('month', models.PositiveIntegerField(default=11)),
                ('year', models.PositiveIntegerField(default=2023)),
                ('is_active', models.BooleanField(default=True)),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('allowance', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='payroll.allowance')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='controller.staff')),
            ],
            options={
                'verbose_name': 'Monthly Allowance',
                'verbose_name_plural': 'Monthly Allowances',
            },
        ),
    ]
