# Generated by Django 4.0.6 on 2023-11-22 13:11

from django.db import migrations, models
import django.db.models.deletion
import payroll.models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0010_bank_type'),
        ('payroll', '0001_payroll'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', payroll.models.NameField(blank=True, max_length=50, null=True)),
                ('name', payroll.models.NameField(blank=True, max_length=512, null=True)),
                ('is_formal', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organization',
            },
        ),
        migrations.RemoveField(
            model_name='deduction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='deduction',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='staffdeduction',
            name='end_date',
        ),
        migrations.AddField(
            model_name='payroll',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payroll',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payroll',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffdeduction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000),
        ),
        migrations.AddField(
            model_name='staffdeduction',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000),
        ),
        migrations.AddField(
            model_name='staffdeduction',
            name='percentage',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='StaffOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=1000)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=1000)),
                ('percentage', models.FloatField(default=0)),
                ('is_percentage', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='payroll.organization')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='controller.staff')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organization',
            },
        ),
        migrations.AddField(
            model_name='monthlydeduction',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='payroll.organization'),
        ),
    ]
