# Generated by Django 4.0.6 on 2023-11-22 14:06

from django.db import migrations, models
import django.db.models.deletion
import payroll.models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0010_bank_type'),
        ('payroll', '0002_payroll_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='account',
            field=payroll.models.NameField(max_length=512, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staffsalary',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='controller.staff', unique=True),
        ),
    ]
