# Generated by Django 4.0.6 on 2023-11-22 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0010_bank_type'),
        ('payroll', '0003_organization_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffsalary',
            name='staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='controller.staff'),
        ),
    ]
