# Generated by Django 4.0.6 on 2023-11-23 06:25

from django.db import migrations, models
import django.db.models.deletion
import payroll.models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_staff_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayeeDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', payroll.models.NameField(blank=True, max_length=50, null=True)),
                ('initia_amount', models.DecimalField(decimal_places=2, default=0, max_digits=1000)),
                ('percentage', models.FloatField(default=0)),
                ('range_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('deduction', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='payroll.deduction')),
            ],
            options={
                'verbose_name': 'Payee Deduction',
                'verbose_name_plural': 'Payee Deductions',
            },
        ),
    ]
