# Generated by Django 4.0.6 on 2023-11-23 06:48

from django.db import migrations, models
import django.db.models.deletion
import payroll.models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0010_bank_type'),
        ('payroll', '0005_payee_deduction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='basic_salary',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='payee',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='security_fund',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='total_allowance',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='total_deduction',
        ),
        migrations.AddField(
            model_name='payroll',
            name='code',
            field=payroll.models.NameField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='total_staff',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='StaffPayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=1000)),
                ('total_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=1000)),
                ('total_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=1000)),
                ('payee', models.DecimalField(decimal_places=2, default=0, max_digits=1000)),
                ('security_fund', models.DecimalField(decimal_places=2, default=0, max_digits=1000)),
                ('month', models.PositiveIntegerField(default=11)),
                ('year', models.PositiveIntegerField(default=2023)),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='controller.staff')),
            ],
            options={
                'verbose_name': 'Staff Payroll',
                'verbose_name_plural': 'Staff Payrolls',
            },
        ),
    ]
