# Generated by Django 4.0.6 on 2023-11-23 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_staff_payroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffpayroll',
            name='payroll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='payroll.payroll'),
            preserve_default=False,
        ),
    ]
