# Generated by Django 4.0.6 on 2023-11-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_staff_pay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deduction',
            name='is_percentage',
        ),
        migrations.AddField(
            model_name='staffdeduction',
            name='is_percentage',
            field=models.BooleanField(default=False),
        ),
    ]
