# Generated by Django 4.0.6 on 2023-12-04 18:01

from django.db import migrations, models
import django.db.models.deletion
import payroll.models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0012_payee_deductions'),
        ('payroll', '0008_deduction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payeededuction',
            old_name='range_deduction',
            new_name='lower_range',
        ),
        migrations.RenameField(
            model_name='payeededuction',
            old_name='percentage',
            new_name='range_percentage',
        ),
        migrations.AddField(
            model_name='payeededuction',
            name='upper_range',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000),
        ),
        migrations.AlterField(
            model_name='monthlyallowance',
            name='month',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='monthlydeduction',
            name='month',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='month',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='staffpayroll',
            name='month',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='staffsalary',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='controller.staff'),
        ),
        migrations.AlterUniqueTogether(
            name='staffsalary',
            unique_together={('staff', 'is_active')},
        ),
        migrations.CreateModel(
            name='SecurityFundDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', payroll.models.NameField(blank=True, max_length=50, null=True)),
                ('percentage', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('deduction', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='payroll.deduction')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='controller.securityfund')),
            ],
            options={
                'verbose_name': 'Payee Deduction',
                'verbose_name_plural': 'Payee Deductions',
            },
        ),
    ]
