# Generated by Django 4.0.6 on 2023-12-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_payee_deductions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Formula variable',
                'verbose_name_plural': 'Formula variables',
            },
        ),
        migrations.CreateModel(
            name='PayrollFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('expression', models.TextField()),
                ('variables', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Payroll Formula',
                'verbose_name_plural': 'Payroll Formulas',
                'unique_together': {('code', 'is_active')},
            },
        ),
    ]
