# Generated by Django 4.0.6 on 2023-12-05 14:22

from django.db import migrations
import payroll.models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_formula'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollformula',
            name='formula_type',
            field=payroll.models.NameField(max_length=255),
            preserve_default=False,
        ),
    ]
