# Generated by Django 4.0.6 on 2023-12-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0011_formula_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowance',
            name='is_repeated',
            field=models.BooleanField(default=False),
        ),
    ]
