# Generated by Django 4.0.6 on 2023-12-06 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0012_allowance_repeate'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyallowance',
            name='date',
            field=models.DateField(default=datetime.date(2023, 12, 6)),
        ),
        migrations.AddField(
            model_name='monthlydeduction',
            name='date',
            field=models.DateField(default=datetime.date(2023, 12, 6)),
        ),
    ]
