# Generated by Django 4.0.6 on 2023-12-06 07:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0013_montly_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyallowance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='monthlydeduction',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
