# Generated by Django 4.0.6 on 2023-12-06 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0012_payee_deductions'),
        ('payroll', '0014_date_cangee'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlyallowance',
            unique_together={('staff', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='monthlydeduction',
            unique_together={('staff', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together={('month', 'year', 'is_approved')},
        ),
        migrations.AlterUniqueTogether(
            name='staffpayroll',
            unique_together={('staff', 'month', 'year')},
        ),
    ]
