# Generated by Django 4.0.6 on 2023-12-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0015_unique_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyallowance',
            name='date_consumed',
            field=models.DateField(null=True),
        ),
    ]
