# Generated by Django 4.0.6 on 2023-12-07 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0016_date_consume'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='formula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='payroll.payrollformula'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffpayroll',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000),
        ),
    ]
