# Generated by Django 4.0.6 on 2023-12-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0017_net_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyallowance',
            name='date_consumed',
        ),
        migrations.AddField(
            model_name='monthlyallowance',
            name='month_consumed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlydeduction',
            name='month_consumed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
