# Generated by Django 4.0.6 on 2023-12-07 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0012_payee_deductions'),
        ('payroll', '0018_month_consume'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlyallowance',
            unique_together={('staff', 'date', 'allowance')},
        ),
        migrations.AlterUniqueTogether(
            name='monthlydeduction',
            unique_together={('staff', 'date', 'deduction')},
        ),
    ]
