# Generated by Django 4.0.6 on 2023-12-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0019_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allowance',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='allowance',
            name='is_percentage',
        ),
        migrations.RemoveField(
            model_name='allowance',
            name='percentage',
        ),
        migrations.AddField(
            model_name='staffallowance',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000),
        ),
        migrations.AddField(
            model_name='staffallowance',
            name='is_percentage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffallowance',
            name='percentage',
            field=models.FloatField(default=0),
        ),
    ]
