# Generated by Django 4.0.6 on 2023-12-27 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0020_change_allowance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlydeduction',
            unique_together=set(),
        ),
    ]
