# Generated by Django 4.0.6 on 2024-05-11 06:10

from django.db import migrations, models
import payroll.models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0021_remove_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffsalary',
            name='acount',
            field=payroll.models.NameField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyallowance',
            name='month',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='monthlyallowance',
            name='year',
            field=models.PositiveIntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='monthlydeduction',
            name='month',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='monthlydeduction',
            name='year',
            field=models.PositiveIntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='month',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='year',
            field=models.PositiveIntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='staffpayroll',
            name='month',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='staffpayroll',
            name='year',
            field=models.PositiveIntegerField(default=2024),
        ),
    ]
