# Generated by Django 4.0.6 on 2024-06-13 19:46

from django.db import migrations, models
import payroll.models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0012_payee_deductions'),
        ('payroll', '0022_finance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffsalary',
            old_name='acount',
            new_name='account_number',
        ),
        migrations.AlterUniqueTogether(
            name='staffsalary',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='staffsalary',
            name='tin_number',
            field=payroll.models.NameField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyallowance',
            name='month',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='monthlydeduction',
            name='month',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='month',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='staffpayroll',
            name='month',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AlterUniqueTogether(
            name='staffsalary',
            unique_together={('staff', 'account_number', 'tin_number', 'is_active')},
        ),
    ]
