# Generated by Django 4.0.6 on 2024-07-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0023_update_tin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyallowance',
            name='month',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='monthlydeduction',
            name='month',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='month',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='staffpayroll',
            name='month',
            field=models.PositiveIntegerField(default=7),
        ),
    ]
