# Generated by Django 4.0.6 on 2024-11-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0015_remove_doc_size'),
        ('payroll', '0024_qlf_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyallowance',
            name='month',
            field=models.PositiveIntegerField(default=11),
        ),
        migrations.AlterField(
            model_name='monthlydeduction',
            name='month',
            field=models.PositiveIntegerField(default=11),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='month',
            field=models.PositiveIntegerField(default=11),
        ),
        migrations.AlterField(
            model_name='staffpayroll',
            name='month',
            field=models.PositiveIntegerField(default=11),
        ),
        migrations.AlterUniqueTogether(
            name='monthlydeduction',
            unique_together={('staff', 'date', 'deduction')},
        ),
    ]
