# Generated by Django 4.0.6 on 2024-11-15 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0025_leave_return_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlydeduction',
            unique_together=set(),
        ),
    ]
