# Generated by Django 4.0.6 on 2025-02-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0026_deduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyallowance',
            name='month',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='monthlyallowance',
            name='year',
            field=models.PositiveIntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name='monthlydeduction',
            name='month',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='monthlydeduction',
            name='year',
            field=models.PositiveIntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='month',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='year',
            field=models.PositiveIntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name='staffpayroll',
            name='month',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='staffpayroll',
            name='year',
            field=models.PositiveIntegerField(default=2025),
        ),
    ]
