# Generated by Django 4.0.6 on 2025-08-04 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0018_cpf'),
        ('payroll', '0030_employee_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyallowance',
            name='month',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='monthlydeduction',
            name='month',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='monthlydeduction',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='payroll.organization'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='month',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='staffpayroll',
            name='month',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AlterUniqueTogether(
            name='monthlydeduction',
            unique_together={('staff', 'date', 'organization', 'deduction')},
        ),
    ]
