# Generated by Django 4.0.6 on 2025-10-21 05:15

from django.db import migrations, models
import django.db.models.deletion
import payroll.models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0031_deduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='securityfunddeduction',
            options={'verbose_name': 'Security Deduction', 'verbose_name_plural': 'Security Deductions'},
        ),
        migrations.AlterField(
            model_name='monthlyallowance',
            name='month',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='monthlydeduction',
            name='month',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='month',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='staffpayroll',
            name='month',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.CreateModel(
            name='HelthDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', payroll.models.NameField(blank=True, max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=1000)),
                ('percentage', models.FloatField(default=0)),
                ('is_amount', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('deduction', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='payroll.deduction')),
            ],
            options={
                'verbose_name': 'Helth Deduction',
                'verbose_name_plural': 'Helth Deductions',
            },
        ),
    ]
