# Generated by Django 4.0.6 on 2025-10-21 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0032_helth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helthdeduction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='helthdeduction',
            name='is_amount',
        ),
    ]
