# Generated by Django 4.0.6 on 2025-10-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0033_helth'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffpayroll',
            name='helth_fund',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000),
        ),
    ]
