# Generated by Django 4.0.6 on 2025-11-26 05:21

from django.db import migrations, models
import payroll.models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0035_scheduler'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', payroll.models.NameField(blank=True, max_length=50, null=True)),
                ('date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Calculation Day',
                'verbose_name_plural': 'Calculation Days',
            },
        ),
    ]
