# Generated by Django 4.0.6 on 2025-11-26 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0036_calculation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculationday',
            name='date',
        ),
    ]
