# Generated by Django 4.0.6 on 2025-11-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0037_calculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationday',
            name='date',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
