# Generated by Django 4.0.6 on 2026-02-07 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0020_health'),
        ('payroll', '0039_health'),
    ]

    operations = [
        migrations.AddField(
            model_name='helthdeduction',
            name='fund',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='controller.healthfund'),
        ),
    ]
