# Generated by Django 4.0.6 on 2026-02-07 11:57

from django.db import migrations
import payroll.models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0020_health'),
        ('payroll', '0040_health'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='staffsalary',
            unique_together={('staff', 'is_active')},
        ),
        migrations.AddField(
            model_name='staffsalary',
            name='branch_code',
            field=payroll.models.NameField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='staffsalary',
            name='customer_number',
            field=payroll.models.NameField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='staffsalary',
            name='ledger',
            field=payroll.models.NameField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='staffsalary',
            name='sub_ledger',
            field=payroll.models.NameField(blank=True, max_length=150, null=True),
        ),
    ]
