# Generated by Django 4.0.6 on 2026-02-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0041_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyallowance',
            name='year_consumed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlydeduction',
            name='year_consumed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
