# Generated by Django 4.0.6 on 2026-02-09 11:04

from django.db import migrations
import payroll.models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0043_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='account',
            field=payroll.models.NameField(blank=True, max_length=512, null=True),
        ),
    ]
