# Generated by Django 4.0.6 on 2026-02-09 11:13

from django.db import migrations
import payroll.models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0044_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='deduction',
            name='branch',
            field=payroll.models.NameField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='deduction',
            name='ledger',
            field=payroll.models.NameField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='deduction',
            name='sub_ledger',
            field=payroll.models.NameField(blank=True, max_length=150, null=True),
        ),
    ]
