# Generated by Django 4.0.6 on 2026-04-22 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0021_account'),
        ('payroll', '0047_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyallowance',
            name='month',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='monthlydeduction',
            name='month',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='month',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='staffpayroll',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='controller.staffdepartment'),
        ),
        migrations.AlterField(
            model_name='staffpayroll',
            name='month',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
