# Generated by Django 4.0.6 on 2026-04-23 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0021_account'),
        ('payroll', '0049_payroll_deduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPayrollAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=1000)),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('allowance', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='payroll.allowance')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='payroll.payroll')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='controller.staff')),
            ],
            options={
                'verbose_name': 'Staff Payroll Allowance',
                'verbose_name_plural': 'Staff Payroll Allowances',
            },
        ),
    ]
