# Generated by Django 4.0.6 on 2026-04-23 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0050_payroll_allowance'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffpayrolldeduction',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='payroll.organization'),
        ),
    ]
