# Generated by Django 4.0.6 on 2026-04-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0051_payroll_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffpayrollallowance',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffpayrolldeduction',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
