# Generated by Django 4.0.6 on 2026-09-23 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0053_kpi'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='staffsalary',
            unique_together=set(),
        ),
    ]
