# Generated by Django 4.0.6 on 2023-11-02 16:27

import dictionary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dictionary_code', dictionary.models.NameField(blank=True, max_length=15, null=True)),
                ('dictionary_name', dictionary.models.NameField(blank=True, max_length=50, null=True)),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Dictionary',
                'verbose_name_plural': 'Dictionaries',
            },
        ),
        migrations.CreateModel(
            name='DictionaryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dictionary_item_code', dictionary.models.NameField(blank=True, max_length=15, null=True)),
                ('dictionary_item_name', dictionary.models.NameField(blank=True, max_length=50, null=True)),
                ('dictionary_item_parent', models.IntegerField(blank=True, null=True)),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dictionary.dictionary')),
            ],
            options={
                'verbose_name': 'Dictionary Item',
                'verbose_name_plural': 'Dictionary Items',
            },
        ),
    ]
