# Generated by Django 4.0.6 on 2023-11-29 06:55

import dictionary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='dictionary_name',
            field=dictionary.models.NameField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='dictionaryitem',
            name='dictionary_item_name',
            field=dictionary.models.NameField(blank=True, max_length=512, null=True),
        ),
    ]
