# Generated by Django 4.0.6 on 2025-08-13 06:13

from django.db import migrations, models
import django.db.models.deletion
import kpi.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictionary', '0002_dict_char'),
        ('controller', '0019_kpi'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('weighting_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Key Result',
                'verbose_name_plural': 'Key Results',
            },
        ),
        migrations.CreateModel(
            name='Kpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', kpi.models.NameField(blank=True, max_length=20, null=True)),
                ('name', kpi.models.NameField(blank=True, max_length=50, null=True)),
                ('descriptions', kpi.models.NameField(blank=True, max_length=512, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('year', models.CharField(blank=True, max_length=15, null=True)),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi', to='controller.staffdepartment')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='dictionary.dictionaryitem')),
            ],
            options={
                'verbose_name': 'Kpi',
                'verbose_name_plural': 'Kips',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', kpi.models.NameField(blank=True, max_length=20, null=True)),
                ('name', kpi.models.NameField(max_length=50)),
                ('descriptions', kpi.models.NameField(blank=True, max_length=512, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='section', to='kpi.kpi')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('performance_measure', models.TextField()),
                ('fy_target', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('actual', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('weighting', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('weighting_rating', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='performance', to='kpi.keyresult')),
            ],
            options={
                'verbose_name': 'Performance',
                'verbose_name_plural': 'Performances',
            },
        ),
        migrations.AddField(
            model_name='keyresult',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='result', to='kpi.section'),
        ),
    ]
