# Generated by Django 4.0.6 on 2025-08-13 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0019_kpi'),
        ('kpi', '0001_kpi'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branchkpi', to='controller.branch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kpi',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departmentkpi', to='controller.department'),
        ),
        migrations.CreateModel(
            name='StaffKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='kpi.kpi')),
                ('perfomance', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='kpi.performance')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='staffkpi', to='controller.staff')),
            ],
            options={
                'verbose_name': 'Staff KPI',
                'verbose_name_plural': 'Staff KPIs',
            },
        ),
    ]
