# Generated by Django 4.0.6 on 2025-08-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0002_staffkpia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='actual',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='weighting_rating',
        ),
        migrations.AddField(
            model_name='staffkpi',
            name='actual',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffkpi',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='staffkpi',
            name='weighting_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='performance',
            name='fy_target',
            field=models.TextField(),
        ),
    ]
