# Generated by Django 4.0.6 on 2025-08-13 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0003_staffkpia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='name',
        ),
    ]
