# Generated by Django 4.0.6 on 2025-08-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0004_staffkpi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffkpi',
            name='actual',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
    ]
