# Generated by Django 4.0.6 on 2025-08-18 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0005_staffkpi'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyresult',
            name='kpi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='kpiresult', to='kpi.kpi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performance',
            name='kpi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='kpiperfomance', to='kpi.kpi'),
            preserve_default=False,
        ),
    ]
