# Generated by Django 4.0.6 on 2026-09-21 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0023_staff_doe'),
        ('kpi', '0006_kpi'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRKPIWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open for Submission'), ('closed', 'Closed'), ('processing', 'Under Evaluation'), ('completed', 'Completed/Archived')], default='draft', max_length=20)),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='KPIKeyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branchresults', to='controller.branch')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departmentresults', to='controller.department')),
            ],
        ),
        migrations.CreateModel(
            name='KPIPerformanceMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('unit_of_measure', models.CharField(default='Percentage', max_length=50)),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('key_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measures', to='kpi.kpikeyresult')),
            ],
        ),
        migrations.CreateModel(
            name='KPISection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffKPIPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Cached sum of weighted ratings', max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted to Manager'), ('approved', 'Approved by Manager'), ('rejected', 'Returned for Corrections')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.PositiveIntegerField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='staff_kpi_periods', to='controller.staff')),
                ('window', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_periods', to='kpi.hrkpiwindow')),
            ],
            options={
                'unique_together': {('window', 'staff')},
            },
        ),
        migrations.CreateModel(
            name='StaffKPIItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('actual_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('weighting', models.DecimalField(decimal_places=2, help_text='Percentage e.g. 20.00 for 20%', max_digits=5)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('weighting_rating', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('key_result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kpi.kpikeyresult')),
                ('kpi_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_items', to='kpi.staffkpiperiod')),
                ('performance_measure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kpi.kpiperformancemeasure')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kpi.kpisection')),
            ],
        ),
        migrations.AddField(
            model_name='kpikeyresult',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_results', to='kpi.kpisection'),
        ),
    ]
