# Generated by Django 4.0.6 on 2026-09-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kpi", "0007_kpi"),
    ]

    operations = [
        migrations.AddField(
            model_name="kpisection",
            name="code",
            field=models.CharField(max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
