# Generated by Django 4.0.6 on 2026-09-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kpi", "0012_kpi_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="hrkpiwindow",
            name="code",
            field=models.CharField(max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="hrkpiwindow",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open for Submission"),
                    ("closed", "Closed"),
                    ("processing", "Under Evaluation"),
                    ("completed", "Completed/Archived"),
                ],
                default="open",
                max_length=20,
            ),
        ),
    ]
