# Generated by Django 4.0.6 on 2026-09-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0013_kpi_window'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrkpiwindow',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
