# Generated by Django 4.0.6 on 2026-09-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0014_kpi_window'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffkpiperiod',
            name='approver_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staffkpiperiod',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
