# Generated by Django 4.0.6 on 2026-09-23 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0023_staff_doe'),
        ('kpi', '0015_kpi_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffkpiperiod',
            old_name='department',
            new_name='station_id',
        ),
        migrations.AddField(
            model_name='staffkpiperiod',
            name='station',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='staffkpiperiod',
            name='station_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staffkpiperiod',
            name='station_supervisor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staffkpiperiod',
            name='station_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='staffkpiperiod',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted to Manager'), ('approved', 'Approved by Manager'), ('rejected', 'Returned for Corrections'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='StaffKPISubmissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submitted', 'Submitted to Supervisor'), ('approved', 'Approved by Supervisor'), ('rejected', 'Returned for Corrections')], max_length=20)),
                ('comments', models.TextField(blank=True, help_text='Reason for rejection, feedback, or approval notes', null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(help_text='Staff or Supervisor who performed this action', on_delete=django.db.models.deletion.RESTRICT, related_name='kpi_actions_taken', to='controller.staff')),
                ('kpi_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_logs', to='kpi.staffkpiperiod')),
            ],
            options={
                'verbose_name': 'Staff KPI Submission Log',
                'verbose_name_plural': 'Staff KPI Submission Logs',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
