# Generated by Django 4.0.6 on 2026-09-23 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0023_staff_doe'),
        ('kpi', '0017_kpi_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffkpiperiod',
            name='station_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='staff_kpi_supervisor', to='controller.staff'),
        ),
    ]
