# Generated by Django 4.0.6 on 2026-09-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0019_section_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffkpiitem',
            name='target_value',
            field=models.CharField(default='0.00', max_length=150),
        ),
    ]
