from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from controller.views import *

#-----------------------------------urls---------------------------------------------

urlpatterns = [
	path('person', PersonAdd.as_view()),
	path('person/update/<int:pk>', PersonUpdate.as_view()),
	path('person/list', PersonList.as_view()),
	path('staff', StaffAdd.as_view()),
	path('staff/update/<int:pk>', StaffUpdate.as_view()),
	path('staff/status/<int:pk>', StaffUpdateStatus.as_view()),
	path('staff/details/<int:pk>', StaffDetails.as_view()),
	path('staff/branch/details', StaffBranchDetails.as_view()),
	path('staff/list', StaffList.as_view()),
	path('staff-qualification', StaffQualificationAdd.as_view()),
	path('staff-qualification/remove', StaffQualificationRemove.as_view()),
	path('staff-qualification/list', StaffQualificationList.as_view()),
	path('supervisor', SupervisorAdd.as_view()),
	path('supervisor/update/<int:pk>', SupervisorUpdate.as_view()),
	path('supervisor/list', SupervisorList.as_view()),
	path('branch', BranchAdd.as_view()),
	path('branch/update/<int:pk>', BranchUpdate.as_view()),
	path('branch/list', BranchList.as_view()),
	path('branch/details/<int:pk>', BranchDetails.as_view()),
	path('department', DepartmentAdd.as_view()),
	path('department/update/<int:pk>', DepartmentUpdate.as_view()),
	path('department/list', DepartmentList.as_view()),
	path('department/details/<int:pk>', DepartmentDetails.as_view()),
	path('department/all/list', DepartmentAllList.as_view()),
	path('department/sub/list', SubDepartmentList.as_view()),
	path('branch-manager', BranchManagerAdd.as_view()),
	path('branch-manager/update/<int:pk>', BranchManagerUpdate.as_view()),
	path('branch-manager/list', BranchManagerList.as_view()),
	path('department-head', DepartmentHeadAdd.as_view()),
	path('department-head/update/<int:pk>', DepartmentHeadUpdate.as_view()),
	path('department-head/list', DepartmentHeadList.as_view()),
	path('staff-department', StaffDepartmentAdd.as_view()),
	path('staff-department/change', StaffDepartmentChange.as_view()),
	path('staff-department/update/<int:pk>', StaffDepartmentUpdate.as_view()),
	path('staff-department/list', StaffDepartmentList.as_view()),
	path('staff/department/branch/list', DepartmentStaffList.as_view()),
	path('staff-department/filter', StaffDepartmentFilter.as_view()),
	path('staff-benefit', StaffBenefitAdd.as_view()),
	path('staff-benefit/update/<int:pk>', StaffBenefitUpdate.as_view()),
	path('staff-benefit/list', StaffBenefitList.as_view()),
	path('staff-benefit-dependant', StaffBenefitDependentAdd.as_view()),
	path('staff-benefit-dependant/update/<int:pk>', StaffBenefitDependentUpdate.as_view()),
	path('staff-benefit-dependant/list', StaffBenefitDependentList.as_view()),
	path('document', DocumentAdd.as_view()),
	path('document/remove', DocumentRemove.as_view()),
	path('document/list', DocumentList.as_view()),
	path('staff-pension', StaffSecurityFundAdd.as_view()),
	path('staff-pension/update/<int:pk>', StaffSecurityFundUpdate.as_view()),
	path('staff-pension/list', StaffSecurityFundList.as_view()),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)