# Generated by Django 4.0.6 on 2023-11-24 14:08

from django.db import migrations, models
import django.db.models.deletion
import training.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictionary', '0001_initial'),
        ('controller', '0010_bank_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', training.models.NameField(blank=True, max_length=50, null=True)),
                ('name', training.models.NameField(blank=True, max_length=512, null=True)),
                ('description', training.models.NameField(blank=True, max_length=512, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('location', training.models.NameField(blank=True, max_length=50, null=True)),
                ('quarter', models.PositiveIntegerField(default=4)),
                ('year', models.PositiveIntegerField(default=2023)),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('satatus', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='training_status', to='dictionary.dictionaryitem')),
                ('training_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dictionary.dictionaryitem')),
            ],
            options={
                'verbose_name': 'Training',
                'verbose_name_plural': 'Trainings',
            },
        ),
        migrations.CreateModel(
            name='TrainingAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='training.training')),
                ('training_attachment', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dictionary.dictionaryitem')),
            ],
            options={
                'verbose_name': 'Training Attachment',
                'verbose_name_plural': 'Training Attachments',
            },
        ),
        migrations.CreateModel(
            name='StaffTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('recorded_by', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='controller.staff')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='training.training')),
            ],
            options={
                'verbose_name': 'Staff Training',
                'verbose_name_plural': 'Staff Trainings',
            },
        ),
    ]
