# Generated by Django 4.0.6 on 2023-11-28 07:17

from django.db import migrations
import training.models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_training'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='location',
            field=training.models.NameField(blank=True, max_length=512, null=True),
        ),
    ]
