# Generated by Django 4.0.6 on 2024-05-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_training_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='quarter',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='training',
            name='year',
            field=models.PositiveIntegerField(default=2024),
        ),
    ]
