# Generated by Django 4.0.6 on 2024-07-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_finance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='quarter',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
