# Generated by Django 4.0.6 on 2024-11-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_qlf_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='quarter',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
