# Generated by Django 4.0.6 on 2025-02-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_leave_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='quarter',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='training',
            name='year',
            field=models.PositiveIntegerField(default=2025),
        ),
    ]
