# Generated by Django 4.0.6 on 2025-10-21 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_deduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='quarter',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
