# Generated by Django 4.0.6 on 2026-02-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_helth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='quarter',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='training',
            name='year',
            field=models.PositiveIntegerField(default=2026),
        ),
    ]
