# Generated by Django 4.0.6 on 2026-09-25 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0012_kpi'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafftraining',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
        migrations.AddField(
            model_name='trainingattachment',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='training.stafftraining'),
        ),
        migrations.AlterField(
            model_name='trainingattachment',
            name='training',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='training.training'),
        ),
    ]
