from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from payroll.views import *

# -----------------------------------urls---------------------------------------------

urlpatterns = [
    path("calculation-day", CalculationDayAdd.as_view()),
    path("calculation-day/list", CalculationDayList.as_view()),
    path("salary", StaffSalaryAdd.as_view()),
    path("salary/update/<int:pk>", StaffSalaryUpdate.as_view()),
    path("salary/list", StaffSalaryList.as_view()),
    path("organization/list", OrganizationList.as_view()),
    path("organization", OrganizationAdd.as_view()),
    path("organization/details/<int:pk>", OrganizationDetail.as_view()),
    path("organization/update/<int:pk>", OrganizationUpdate.as_view()),
    path("staff-organization", StaffOrganizationAdd.as_view()),
    path("staff-organization/update/<int:pk>", StaffOrganizationUpdate.as_view()),
    path("staff-organization/list", StaffOrganizationList.as_view()),
    path("allowance/list", AllowanceList.as_view()),
    path("allowance", AllowanceAdd.as_view()),
    path("allowance/update/<int:pk>", AllowanceUpdate.as_view()),
    path("allowance/details/<int:pk>", AllowanceDetail.as_view()),
    path("deduction", DeductionAdd.as_view()),
    path("deduction/update/<int:pk>", DeductionUpdate.as_view()),
    path("deduction/details/<int:pk>", DeductionDetail.as_view()),
    path("deduction/list", DeductionList.as_view()),
    path("staff-allowance", StaffAllowanceAdd.as_view()),
    path("staff-allowance/update/<int:pk>", StaffAllowanceUpdate.as_view()),
    path("staff-allowance/list", StaffAllowanceList.as_view()),
    path("staff-deduction", StaffDeductionAdd.as_view()),
    path("staff-deduction/update/<int:pk>", StaffDeductionUpdate.as_view()),
    path("staff-deduction/list", StaffDeductionList.as_view()),
    path("payee-deduction", PayeeDeductionAdd.as_view()),
    path("payee-deduction/update/<int:pk>", PayeeDeductionUpdate.as_view()),
    path("payee-deduction/list", PayeeDeductionList.as_view()),
    path("pension", SecurityFundAdd.as_view()),
    path("pension/update/<int:pk>", SecurityFundUpdate.as_view()),
    path("pension/details/<int:pk>", SecurityFundDetail.as_view()),
    path("pension/list", SecurityFundList.as_view()),
    path("monthly-allowance", MonthlyAllowanceAdd.as_view()),
    path("monthly-allowance/update/<int:pk>", MonthlyAllowanceUpdate.as_view()),
    path("monthly-allowance/list", MonthlyAllowanceList.as_view()),
    path("monthly-allowance/delete", MonthlyAllowanceDelete.as_view()),
    path("monthly-deduction", MonthlyDeductionAdd.as_view()),
    path("monthly-deduction/update/<int:pk>", MonthlyDeductionUpdate.as_view()),
    path("monthly-deduction/list", MonthlyDeductionList.as_view()),
    path("monthly-deduction/delete", MonthlyDeductionDelete.as_view()),
    path("payroll/generate", GeneratePayroll.as_view()),
    path("payroll", ProcessPayroll.as_view()),
    path("payroll/freeze", PayrollFreeze.as_view()),
    path("payroll/details/<int:pk>", PayrollDetail.as_view()),
    path("payroll/update/<int:pk>", PayrollUpdate.as_view()),
    path("payroll/list", PayrollList.as_view()),
    path("staff-payroll", StaffPayrollAdd.as_view()),
    path("staff-payroll/update/<int:pk>", StaffPayrollUpdate.as_view()),
    path("staff-payroll/list", StaffPayrollList.as_view()),
    path("payroll-formula", PayrollFormulaAdd.as_view()),
    path("payroll-formula/list", PayrollFormulaList.as_view()),
    path("payroll-variable", PayrollVariableAdd.as_view()),
    path("payroll-variable/list", PayrollVariableList.as_view()),
    path("payroll-summary", PayrollSummary.as_view()),
    path("payroll-allowance-summary", PayrollAllowanceSummary.as_view()),
    path("payroll-deduction-summary", PayrollDeductionSummary.as_view()),
    path(
        "payroll-contribution-allowance-summary",
        PayrollContributionAllowanceSummary.as_view(),
    ),
    path(
        "payroll-contribution-deduction-summary",
        PayrollContributionDeductionSummary.as_view(),
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
